services:
  frontend:
    image: ghcr.io/yazan93farah/conduit-frontend:latest
    # environment:
    #   FRONTEND_ANGULAR_HOST_PORT: "${FRONTEND_ANGULAR_HOST_PORT:-8282}"
    #   FRONTEND_SERVER_API_URL: "${FRONTEND_SERVER_API_URL:-http://backend:5000/api}"
    env_file:
      - frontend.env
    ports:
      - "${FRONTEND_ANGULAR_HOST_PORT:-8282}:80"
    restart: unless-stopped
    networks:
      - conduit

  database:
    image: postgres:9.6
    env_file:
      - database.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - conduit

  backend:
    image: ghcr.io/yazan93farah/conduit-backend:latest
    # environment:
    #   BACKEND_DJANGO_HOST_PORT: "${BACKEND_DJANGO_HOST_PORT:-5000}"
    env_file:
      - backend.env
      - database.env
    ports:
      - "${BACKEND_DJANGO_HOST_PORT:-5000}:5000"
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - conduit

volumes:
  postgres_data:

networks:
  conduit:
