services:
  frontend:
    build:
      context: ./conduit-frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    environment:
      ANGULAR_HOST_PORT: "${ANGULAR_HOST_PORT:-8282}"
      API_URL: "${API_URL:-http://localhost:5000/api}"
    ports:
      - "${ANGULAR_HOST_PORT:-8282}:80"
    restart: unless-stopped
    networks:
      - conduit
  database:
    image: postgres:9.6
    container_name: database-container
    env_file:
      - .database.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
    - conduit
  backend:
    build:
      context: ./conduit-backend
      dockerfile: Dockerfile
    container_name: backend-container
    environment:
      DJANGO_HOST_PORT: "${DJANGO_HOST_PORT:-5000}"
    env_file:
      - ./conduit-backend/.env
      - .database.env
    ports:
      - "${DJANGO_HOST_PORT:-5000}:5000"
    restart: unless-stopped
    networks:
      - conduit
    depends_on:
      - database
volumes:
  postgres_data:
networks:
  conduit:
