services:
  frontend:
    build:
      context: ./conduit-frontend
      dockerfile: Dockerfile
    container_name: frontend

    environment:
      ANGULAR_HOST_PORT: "${ANGULAR_HOST_PORT:-8282}"
      API_URL: "${API_URL:-http://localhost:5000/api}"

    ports:
      - "${ANGULAR_HOST_PORT:-8282}:80"
    restart: unless-stopped
    networks:
      - conduit

  backend:
    build:
      context: ./conduit-backend
      dockerfile: Dockerfile
    environment:
      DJANGO_HOST_PORT: "${DJANGO_HOST_PORT:-5000}"
    env_file:
    - ./conduit-backend/.env
    ports:
      - "${DJANGO_HOST_PORT:-5000}:5000"
    volumes:
      - backend_data:/app   
    restart: unless-stopped
    networks:
      - conduit


volumes:
  backend_data:
networks:
    conduit: