name: deployment

on:
  push:
    branches:
      - master
      - ghActions-deployment-workflow
  workflow_dispatch:


jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          if_key_exists: fail
          known_hosts: unnecessary


      - name: Add VM to known_hostsv
        run: |
          ssh-keyscan -H "${{ secrets.VM_HOST }}" >> ~/.ssh/known_hosts

      - name: SSH connection test
        run: |
          ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} \
            "echo 'SSH OK' && uname -a && docker --version && docker compose version"
